class BlazzerRunner {
    public static void main(String args[]) {

        Blazzer b1 = new Blazzer();
        b1.brand = "Louis Philippe";
        b1.size = "M";
        b1.color = "Black";
        b1.price = 3499.0;
        b1.isFormal = true;
        b1.material = "Wool";
        System.out.println("b1.brand: " + b1.brand);
        System.out.println("b1.size: " + b1.size);
        System.out.println("b1.color: " + b1.color);
        System.out.println("b1.price: " + b1.price);
        System.out.println("b1.isFormal: " + b1.isFormal);
        System.out.println("b1.material: " + b1.material);

        Blazzer b2 = new Blazzer();
        b2.brand = "Arrow";
        b2.size = "L";
        b2.color = "Navy";
        b2.price = 3799.0;
        b2.isFormal = true;
        b2.material = "Cotton";
        System.out.println("b2.brand: " + b2.brand);
        System.out.println("b2.size: " + b2.size);
        System.out.println("b2.color: " + b2.color);
        System.out.println("b2.price: " + b2.price);
        System.out.println("b2.isFormal: " + b2.isFormal);
        System.out.println("b2.material: " + b2.material);

        Blazzer b3 = new Blazzer();
        b3.brand = "Peter England";
        b3.size = "S";
        b3.color = "Grey";
        b3.price = 2899.0;
        b3.isFormal = false;
        b3.material = "Linen";
        System.out.println("b3.brand: " + b3.brand);
        System.out.println("b3.size: " + b3.size);
        System.out.println("b3.color: " + b3.color);
        System.out.println("b3.price: " + b3.price);
        System.out.println("b3.isFormal: " + b3.isFormal);
        System.out.println("b3.material: " + b3.material);

        Blazzer b4 = new Blazzer();
        b4.brand = "Van Heusen";
        b4.size = "XL";
        b4.color = "Brown";
        b4.price = 4099.0;
        b4.isFormal = true;
        b4.material = "Wool";
        System.out.println("b4.brand: " + b4.brand);
        System.out.println("b4.size: " + b4.size);
        System.out.println("b4.color: " + b4.color);
        System.out.println("b4.price: " + b4.price);
        System.out.println("b4.isFormal: " + b4.isFormal);
        System.out.println("b4.material: " + b4.material);

        Blazzer b5 = new Blazzer();
        b5.brand = "Park Avenue";
        b5.size = "M";
        b5.color = "Maroon";
        b5.price = 3599.0;
        b5.isFormal = false;
        b5.material = "Silk";
        System.out.println("b5.brand: " + b5.brand);
        System.out.println("b5.size: " + b5.size);
        System.out.println("b5.color: " + b5.color);
        System.out.println("b5.price: " + b5.price);
        System.out.println("b5.isFormal: " + b5.isFormal);
        System.out.println("b5.material: " + b5.material);

        Blazzer b6 = new Blazzer();
        b6.brand = "Raymond";
        b6.size = "L";
        b6.color = "Olive";
        b6.price = 3999.0;
        b6.isFormal = true;
        b6.material = "Wool Blend";
        System.out.println("b6.brand: " + b6.brand);
        System.out.println("b6.size: " + b6.size);
        System.out.println("b6.color: " + b6.color);
        System.out.println("b6.price: " + b6.price);
        System.out.println("b6.isFormal: " + b6.isFormal);
        System.out.println("b6.material: " + b6.material);

        Blazzer b7 = new Blazzer();
        b7.brand = "Blackberrys";
        b7.size = "M";
        b7.color = "Beige";
        b7.price = 2699.0;
        b7.isFormal = true;
        b7.material = "Cotton Blend";
        System.out.println("b7.brand: " + b7.brand);
        System.out.println("b7.size: " + b7.size);
        System.out.println("b7.color: " + b7.color);
        System.out.println("b7.price: " + b7.price);
        System.out.println("b7.isFormal: " + b7.isFormal);
        System.out.println("b7.material: " + b7.material);

        Blazzer b8 = new Blazzer();
        b8.brand = "H&M";
        b8.size = "S";
        b8.color = "Blue";
        b8.price = 3199.0;
        b8.isFormal = false;
        b8.material = "Denim";
        System.out.println("b8.brand: " + b8.brand);
        System.out.println("b8.size: " + b8.size);
        System.out.println("b8.color: " + b8.color);
        System.out.println("b8.price: " + b8.price);
        System.out.println("b8.isFormal: " + b8.isFormal);
        System.out.println("b8.material: " + b8.material);

        Blazzer b9 = new Blazzer();
        b9.brand = "Zara";
        b9.size = "M";
        b9.color = "Charcoal";
        b9.price = 3899.0;
        b9.isFormal = true;
        b9.material = "Tweed";
        System.out.println("b9.brand: " + b9.brand);
        System.out.println("b9.size: " + b9.size);
        System.out.println("b9.color: " + b9.color);
        System.out.println("b9.price: " + b9.price);
        System.out.println("b9.isFormal: " + b9.isFormal);
        System.out.println("b9.material: " + b9.material);

        Blazzer b10 = new Blazzer();
        b10.brand = "Allen Solly";
        b10.size = "L";
        b10.color = "Light Grey";
        b10.price = 2799.0;
        b10.isFormal = false;
        b10.material = "Polyester";
        System.out.println("b10.brand: " + b10.brand);
        System.out.println("b10.size: " + b10.size);
        System.out.println("b10.color: " + b10.color);
        System.out.println("b10.price: " + b10.price);
        System.out.println("b10.isFormal: " + b10.isFormal);
        System.out.println("b10.material: " + b10.material);
		
		Blazzer b11 = new Blazzer();
        b11.brand = "Uniqlo";
        b11.size = "XL";
        b11.color = "Steel Blue";
        b11.price = 3599.0;
        b11.isFormal = true;
        b11.material = "Cotton";
        System.out.println("b11.brand: " + b11.brand);
        System.out.println("b11.size: " + b11.size);
        System.out.println("b11.color: " + b11.color);
        System.out.println("b11.price: " + b11.price);
        System.out.println("b11.isFormal: " + b11.isFormal);
        System.out.println("b11.material: " + b11.material);

        Blazzer b12 = new Blazzer();
        b12.brand = "Next";
        b12.size = "M";
        b12.color = "Olive Green";
        b12.price = 3099.0;
        b12.isFormal = false;
        b12.material = "Cotton Blend";
        System.out.println("b12.brand: " + b12.brand);
        System.out.println("b12.size: " + b12.size);
        System.out.println("b12.color: " + b12.color);
        System.out.println("b12.price: " + b12.price);
        System.out.println("b12.isFormal: " + b12.isFormal);
        System.out.println("b12.material: " + b12.material);

        Blazzer b13 = new Blazzer();
        b13.brand = "Jack & Jones";
        b13.size = "L";
        b13.color = "Tan";
        b13.price = 3399.0;
        b13.isFormal = true;
        b13.material = "Wool Blend";
        System.out.println("b13.brand: " + b13.brand);
        System.out.println("b13.size: " + b13.size);
        System.out.println("b13.color: " + b13.color);
        System.out.println("b13.price: " + b13.price);
        System.out.println("b13.isFormal: " + b13.isFormal);
        System.out.println("b13.material: " + b13.material);

        Blazzer b14 = new Blazzer();
        b14.brand = "Marks & Spencer";
        b14.size = "S";
        b14.color = "Camel";
        b14.price = 3890.0;
        b14.isFormal = false;
        b14.material = "Linen";
        System.out.println("b14.brand: " + b14.brand);
        System.out.println("b14.size: " + b14.size);
        System.out.println("b14.color: " + b14.color);
        System.out.println("b14.price: " + b14.price);
        System.out.println("b14.isFormal: " + b14.isFormal);
        System.out.println("b14.material: " + b14.material);

        Blazzer b15 = new Blazzer();
        b15.brand = "Forever 21";
        b15.size = "M";
        b15.color = "Dusty Pink";
        b15.price = 2499.0;
        b15.isFormal = false;
        b15.material = "Polyester";
        System.out.println("b15.brand: " + b15.brand);
        System.out.println("b15.size: " + b15.size);
        System.out.println("b15.color: " + b15.color);
        System.out.println("b15.price: " + b15.price);
        System.out.println("b15.isFormal: " + b15.isFormal);
        System.out.println("b15.material: " + b15.material);

        Blazzer b16 = new Blazzer();
        b16.brand = "Calvin Klein";
        b16.size = "L";
        b16.color = "Jet Black";
        b16.price = 4599.0;
        b16.isFormal = true;
        b16.material = "Wool";
        System.out.println("b16.brand: " + b16.brand);
        System.out.println("b16.size: " + b16.size);
        System.out.println("b16.color: " + b16.color);
        System.out.println("b16.price: " + b16.price);
        System.out.println("b16.isFormal: " + b16.isFormal);
        System.out.println("b16.material: " + b16.material);

        Blazzer b17 = new Blazzer();
        b17.brand = "Gucci";
        b17.size = "XL";
        b17.color = "Ivory";
        b17.price = 7499.0;
        b17.isFormal = true;
        b17.material = "Silk";
        System.out.println("b17.brand: " + b17.brand);
        System.out.println("b17.size: " + b17.size);
        System.out.println("b17.color: " + b17.color);
        System.out.println("b17.price: " + b17.price);
        System.out.println("b17.isFormal: " + b17.isFormal);
        System.out.println("b17.material: " + b17.material);

        Blazzer b18 = new Blazzer();
        b18.brand = "Tommy Hilfiger";
        b18.size = "M";
        b18.color = "Cream";
        b18.price = 4299.0;
        b18.isFormal = false;
        b18.material = "Cotton";
        System.out.println("b18.brand: " + b18.brand);
        System.out.println("b18.size: " + b18.size);
        System.out.println("b18.color: " + b18.color);
        System.out.println("b18.price: " + b18.price);
        System.out.println("b18.isFormal: " + b18.isFormal);
        System.out.println("b18.material: " + b18.material);

        Blazzer b19 = new Blazzer();
        b19.brand = "Levi's";
        b19.size = "S";
        b19.color = "Sky Blue";
        b19.price = 2899.0;
        b19.isFormal = false;
        b19.material = "Denim";
        System.out.println("b19.brand: " + b19.brand);
        System.out.println("b19.size: " + b19.size);
        System.out.println("b19.color: " + b19.color);
        System.out.println("b19.price: " + b19.price);
        System.out.println("b19.isFormal: " + b19.isFormal);
        System.out.println("b19.material: " + b19.material);

        Blazzer b20 = new Blazzer();
        b20.brand = "Puma";
        b20.size = "L";
        b20.color = "Navy Blue";
        b20.price = 3199.0;
        b20.isFormal = true;
        b20.material = "Polyester Blend";
        System.out.println("b20.brand: " + b20.brand);
        System.out.println("b20.size: " + b20.size);
        System.out.println("b20.color: " + b20.color);
        System.out.println("b20.price: " + b20.price);
        System.out.println("b20.isFormal: " + b20.isFormal);
        System.out.println("b20.material: " + b20.material);

    }
}
