class CourtCaseRunner {
    public static void main(String[] args) {

        CourtCase c1 = new CourtCase();
        c1.caseNumber = "CR123";
        c1.caseType = "Criminal";
        c1.plaintiff = "State";
        c1.defendant = "Ravi Kumar";
        c1.courtName = "Bangalore District Court";
        c1.judgeName = "Justice Rao";
        c1.filingDate = "2023-01-10";
        c1.hearingDate = "2023-07-20";
        c1.status = "Pending";
        c1.isCriminal = true;
        System.out.println("c1.caseNumber: " + c1.caseNumber);

        CourtCase c2 = new CourtCase();
        c2.caseNumber = "CV456";
        c2.caseType = "Civil";
        c2.plaintiff = "Ramesh";
        c2.defendant = "Suresh";
        c2.courtName = "Chennai High Court";
        c2.judgeName = "Justice Aruna";
        c2.filingDate = "2022-03-15";
        c2.hearingDate = "2023-10-12";
        c2.status = "Ongoing";
        c2.isCriminal = false;
        System.out.println("c2.caseNumber: " + c2.caseNumber);

        CourtCase c3 = new CourtCase();
        c3.caseNumber = "CR789";
        c3.caseType = "Criminal";
        c3.plaintiff = "State";
        c3.defendant = "Anil Sharma";
        c3.courtName = "Mumbai Session Court";
        c3.judgeName = "Justice Patel";
        c3.filingDate = "2021-06-25";
        c3.hearingDate = "2023-08-18";
        c3.status = "Judgement Reserved";
        c3.isCriminal = true;
        System.out.println("c3.caseNumber: " + c3.caseNumber);

        CourtCase c4 = new CourtCase();
        c4.caseNumber = "CV101";
        c4.caseType = "Family";
        c4.plaintiff = "Kiran";
        c4.defendant = "Meena";
        c4.courtName = "Delhi Family Court";
        c4.judgeName = "Justice Sinha";
        c4.filingDate = "2020-12-01";
        c4.hearingDate = "2023-09-01";
        c4.status = "Closed";
        c4.isCriminal = false;
        System.out.println("c4.caseNumber: " + c4.caseNumber);

        CourtCase c5 = new CourtCase();
        c5.caseNumber = "CR202";
        c5.caseType = "Criminal";
        c5.plaintiff = "CBI";
        c5.defendant = "Ajay Mishra";
        c5.courtName = "Lucknow CBI Court";
        c5.judgeName = "Justice Yadav";
        c5.filingDate = "2022-07-20";
        c5.hearingDate = "2023-11-22";
        c5.status = "Under Trial";
        c5.isCriminal = true;
        System.out.println("c5.caseNumber: " + c5.caseNumber);

        CourtCase c6 = new CourtCase();
        c6.caseNumber = "CV303";
        c6.caseType = "Property";
        c6.plaintiff = "Shalini";
        c6.defendant = "Rajesh";
        c6.courtName = "Hyderabad Civil Court";
        c6.judgeName = "Justice Prasad";
        c6.filingDate = "2023-02-14";
        c6.hearingDate = "2023-09-18";
        c6.status = "Ongoing";
        c6.isCriminal = false;
        System.out.println("c6.caseNumber: " + c6.caseNumber);

        CourtCase c7 = new CourtCase();
        c7.caseNumber = "CV404";
        c7.caseType = "Tax";
        c7.plaintiff = "IT Dept";
        c7.defendant = "XYZ Pvt Ltd";
        c7.courtName = "Delhi High Court";
        c7.judgeName = "Justice Raman";
        c7.filingDate = "2021-10-01";
        c7.hearingDate = "2023-08-05";
        c7.status = "Pending";
        c7.isCriminal = false;
        System.out.println("c7.caseNumber: " + c7.caseNumber);

        CourtCase c8 = new CourtCase();
        c8.caseNumber = "CR505";
        c8.caseType = "Criminal";
        c8.plaintiff = "State";
        c8.defendant = "Naveen Reddy";
        c8.courtName = "Secunderabad Session Court";
        c8.judgeName = "Justice Kumar";
        c8.filingDate = "2022-01-05";
        c8.hearingDate = "2023-07-25";
        c8.status = "Convicted";
        c8.isCriminal = true;
        System.out.println("c8.caseNumber: " + c8.caseNumber);

        CourtCase c9 = new CourtCase();
        c9.caseNumber = "CV606";
        c9.caseType = "Labor";
        c9.plaintiff = "Anita";
        c9.defendant = "ABC Corp";
        c9.courtName = "Labour Court Pune";
        c9.judgeName = "Justice Shetty";
        c9.filingDate = "2021-09-15";
        c9.hearingDate = "2023-08-30";
        c9.status = "Dismissed";
        c9.isCriminal = false;
        System.out.println("c9.caseNumber: " + c9.caseNumber);

        CourtCase c10 = new CourtCase();
        c10.caseNumber = "CR707";
        c10.caseType = "Criminal";
        c10.plaintiff = "Police";
        c10.defendant = "John Doe";
        c10.courtName = "Goa District Court";
        c10.judgeName = "Justice Naik";
        c10.filingDate = "2020-05-20";
        c10.hearingDate = "2023-12-15";
        c10.status = "Under Investigation";
        c10.isCriminal = true;
        System.out.println("c10.caseNumber: " + c10.caseNumber);

        CourtCase c11 = new CourtCase();
        c11.caseNumber = "CV808";
        c11.caseType = "Consumer";
        c11.plaintiff = "Priya";
        c11.defendant = "Retail Co.";
        c11.courtName = "Consumer Forum Delhi";
        c11.judgeName = "Justice Bhat";
        c11.filingDate = "2023-03-18";
        c11.hearingDate = "2023-09-28";
        c11.status = "Ongoing";
        c11.isCriminal = false;
        System.out.println("c11.caseNumber: " + c11.caseNumber);

        CourtCase c12 = new CourtCase();
        c12.caseNumber = "CR909";
        c12.caseType = "Criminal";
        c12.plaintiff = "CBI";
        c12.defendant = "Unknown";
        c12.courtName = "CBI Special Court";
        c12.judgeName = "Justice Rao";
        c12.filingDate = "2021-01-01";
        c12.hearingDate = "2024-01-15";
        c12.status = "Pending";
        c12.isCriminal = true;
        System.out.println("c12.caseNumber: " + c12.caseNumber);

        CourtCase c13 = new CourtCase();
        c13.caseNumber = "CV111";
        c13.caseType = "Contract";
        c13.plaintiff = "Zed Corp";
        c13.defendant = "PrimeBuild Ltd";
        c13.courtName = "Bangalore Civil Court";
        c13.judgeName = "Justice Venu";
        c13.filingDate = "2022-11-11";
        c13.hearingDate = "2023-08-08";
        c13.status = "Settled";
        c13.isCriminal = false;
        System.out.println("c13.caseNumber: " + c13.caseNumber);

        CourtCase c14 = new CourtCase();
        c14.caseNumber = "CR212";
        c14.caseType = "Criminal";
        c14.plaintiff = "ED";
        c14.defendant = "Ashok Mehta";
        c14.courtName = "Special ED Court";
        c14.judgeName = "Justice Rao";
        c14.filingDate = "2023-04-10";
        c14.hearingDate = "2023-12-22";
        c14.status = "Ongoing";
        c14.isCriminal = true;
        System.out.println("c14.caseNumber: " + c14.caseNumber);

        CourtCase c15 = new CourtCase();
        c15.caseNumber = "CV313";
        c15.caseType = "Land Dispute";
        c15.plaintiff = "Rahim";
        c15.defendant = "Shankar";
        c15.courtName = "Tumkur Civil Court";
        c15.judgeName = "Justice Meena";
        c15.filingDate = "2022-06-06";
        c15.hearingDate = "2023-09-15";
        c15.status = "Ongoing";
        c15.isCriminal = false;
        System.out.println("c15.caseNumber: " + c15.caseNumber);

        CourtCase c16 = new CourtCase();
        c16.caseNumber = "CV414";
        c16.caseType = "Divorce";
        c16.plaintiff = "Rita";
        c16.defendant = "Sam";
        c16.courtName = "Family Court Chennai";
        c16.judgeName = "Justice Sangeetha";
        c16.filingDate = "2022-02-02";
        c16.hearingDate = "2023-08-22";
        c16.status = "Closed";
        c16.isCriminal = false;
        System.out.println("c16.caseNumber: " + c16.caseNumber);

        CourtCase c17 = new CourtCase();
        c17.caseNumber = "CR515";
        c17.caseType = "Criminal";
        c17.plaintiff = "State";
        c17.defendant = "Jacob";
        c17.courtName = "Kolkata Sessions Court";
        c17.judgeName = "Justice Mitra";
        c17.filingDate = "2020-11-01";
        c17.hearingDate = "2023-08-10";
        c17.status = "Acquitted";
        c17.isCriminal = true;
        System.out.println("c17.caseNumber: " + c17.caseNumber);

        CourtCase c18 = new CourtCase();
        c18.caseNumber = "CV616";
        c18.caseType = "Inheritance";
        c18.plaintiff = "Deepa";
        c18.defendant = "Manoj";
        c18.courtName = "Family Court Kochi";
        c18.judgeName = "Justice Nair";
        c18.filingDate = "2021-07-17";
        c18.hearingDate = "2023-10-01";
        c18.status = "Ongoing";
        c18.isCriminal = false;
        System.out.println("c18.caseNumber: " + c18.caseNumber);

        CourtCase c19 = new CourtCase();
        c19.caseNumber = "CR717";
        c19.caseType = "Cyber Crime";
        c19.plaintiff = "Cyber Cell";
        c19.defendant = "Unknown";
        c19.courtName = "Cyber Crime Court";
        c19.judgeName = "Justice Arvind";
        c19.filingDate = "2023-01-30";
        c19.hearingDate = "2023-09-09";
        c19.status = "Investigating";
        c19.isCriminal = true;
        System.out.println("c19.caseNumber: " + c19.caseNumber);

        CourtCase c20 = new CourtCase();
        c20.caseNumber = "CV818";
        c20.caseType = "Education";
        c20.plaintiff = "Student Union";
        c20.defendant = "University X";
        c20.courtName = "Education Tribunal";
        c20.judgeName = "Justice Kulkarni";
        c20.filingDate = "2023-06-01";
        c20.hearingDate = "2023-09-20";
        c20.status = "Ongoing";
        c20.isCriminal = false;
        System.out.println("c20.caseNumber: " + c20.caseNumber);
    }
}
