class CrackersRunner {
    public static void main(String args[]) {
        Crackers c1 = new Crackers();
        c1.name = "Flower Pot";
        c1.type = "Ground";
        c1.price = 50.0;
        c1.isLoud = false;
        c1.isColorful = true;
        c1.brand = "Standard";
        c1.shape = "Cone";
        c1.weight = 150.0;
        c1.madeIn = "Sivakasi";
        c1.duration = 5;
        System.out.println("c1.name: " + c1.name);

        Crackers c2 = new Crackers();
        c2.name = "Rocket";
        c2.type = "Aerial";
        c2.price = 30.0;
        c2.isLoud = true;
        c2.isColorful = true;
        c2.brand = "Ajanta";
        c2.shape = "Stick";
        c2.weight = 80.0;
        c2.madeIn = "Delhi";
        c2.duration = 3;

        Crackers c3 = new Crackers();
        c3.name = "Sparklers";
        c3.type = "Handheld";
        c3.price = 25.0;
        c3.isLoud = false;
        c3.isColorful = true;
        c3.brand = "Anil";
        c3.shape = "Stick";
        c3.weight = 60.0;
        c3.madeIn = "Tamil Nadu";
        c3.duration = 4;

        Crackers c4 = new Crackers();
        c4.name = "Bijili";
        c4.type = "Sound";
        c4.price = 15.0;
        c4.isLoud = true;
        c4.isColorful = false;
        c4.brand = "Standard";
        c4.shape = "Twisted";
        c4.weight = 20.0;
        c4.madeIn = "UP";
        c4.duration = 1;

        Crackers c5 = new Crackers();
        c5.name = "Chakri";
        c5.type = "Ground Spin";
        c5.price = 40.0;
        c5.isLoud = false;
        c5.isColorful = true;
        c5.brand = "Noble";
        c5.shape = "Flat Disc";
        c5.weight = 70.0;
        c5.madeIn = "Sivakasi";
        c5.duration = 6;

        Crackers c6 = new Crackers();
        c6.name = "Bomb";
        c6.type = "Sound";
        c6.price = 60.0;
        c6.isLoud = true;
        c6.isColorful = false;
        c6.brand = "King";
        c6.shape = "Round";
        c6.weight = 100.0;
        c6.madeIn = "Bangalore";
        c6.duration = 2;

        Crackers c7 = new Crackers();
        c7.name = "Colour Matches";
        c7.type = "Light";
        c7.price = 10.0;
        c7.isLoud = false;
        c7.isColorful = true;
        c7.brand = "Hero";
        c7.shape = "Stick";
        c7.weight = 15.0;
        c7.madeIn = "Kolkata";
        c7.duration = 2;

        Crackers c8 = new Crackers();
        c8.name = "Ground Wheel";
        c8.type = "Ground";
        c8.price = 45.0;
        c8.isLoud = false;
        c8.isColorful = true;
        c8.brand = "Super";
        c8.shape = "Circle";
        c8.weight = 90.0;
        c8.madeIn = "TN";
        c8.duration = 5;

        Crackers c9 = new Crackers();
        c9.name = "Deluxe Rocket";
        c9.type = "Aerial";
        c9.price = 70.0;
        c9.isLoud = true;
        c9.isColorful = true;
        c9.brand = "Supreme";
        c9.shape = "Tube";
        c9.weight = 110.0;
        c9.madeIn = "Pune";
        c9.duration = 6;

        Crackers c10 = new Crackers();
        c10.name = "Twinkling Stars";
        c10.type = "Aerial";
        c10.price = 55.0;
        c10.isLoud = false;
        c10.isColorful = true;
        c10.brand = "Glory";
        c10.shape = "Round";
        c10.weight = 95.0;
        c10.madeIn = "Hyderabad";
        c10.duration = 4;

        Crackers c11 = new Crackers();
        c11.name = "Hydrogen Bomb";
        c11.type = "Sound";
        c11.price = 80.0;
        c11.isLoud = true;
        c11.isColorful = false;
        c11.brand = "Bombay Fireworks";
        c11.shape = "Box";
        c11.weight = 120.0;
        c11.madeIn = "Mumbai";
        c11.duration = 3;

        Crackers c12 = new Crackers();
        c12.name = "Snake Tablets";
        c12.type = "Ground";
        c12.price = 20.0;
        c12.isLoud = false;
        c12.isColorful = false;
        c12.brand = "SnakeFire";
        c12.shape = "Tablet";
        c12.weight = 10.0;
        c12.madeIn = "Chennai";
        c12.duration = 5;

        Crackers c13 = new Crackers();
        c13.name = "Ribbon Bomb";
        c13.type = "Sound";
        c13.price = 45.0;
        c13.isLoud = true;
        c13.isColorful = false;
        c13.brand = "Ribbon";
        c13.shape = "Cylinder";
        c13.weight = 95.0;
        c13.madeIn = "Kerala";
        c13.duration = 2;

        Crackers c14 = new Crackers();
        c14.name = "Mini Rocket";
        c14.type = "Aerial";
        c14.price = 25.0;
        c14.isLoud = false;
        c14.isColorful = true;
        c14.brand = "Orbit";
        c14.shape = "Stick";
        c14.weight = 60.0;
        c14.madeIn = "Sivakasi";
        c14.duration = 3;

        Crackers c15 = new Crackers();
        c15.name = "Twister";
        c15.type = "Spin";
        c15.price = 35.0;
        c15.isLoud = false;
        c15.isColorful = true;
        c15.brand = "TwistFire";
        c15.shape = "Spiral";
        c15.weight = 80.0;
        c15.madeIn = "MP";
        c15.duration = 4;

        Crackers c16 = new Crackers();
        c16.name = "Star Light";
        c16.type = "Handheld";
        c16.price = 20.0;
        c16.isLoud = false;
        c16.isColorful = true;
        c16.brand = "SkyGlow";
        c16.shape = "Stick";
        c16.weight = 25.0;
        c16.madeIn = "Punjab";
        c16.duration = 3;

        Crackers c17 = new Crackers();
        c17.name = "Chain Bomb";
        c17.type = "Sound";
        c17.price = 70.0;
        c17.isLoud = true;
        c17.isColorful = false;
        c17.brand = "ChainFire";
        c17.shape = "String";
        c17.weight = 130.0;
        c17.madeIn = "Odisha";
        c17.duration = 5;

        Crackers c18 = new Crackers();
        c18.name = "Magic Pencil";
        c18.type = "Light";
        c18.price = 18.0;
        c18.isLoud = false;
        c18.isColorful = true;
        c18.brand = "Shine";
        c18.shape = "Cylinder";
        c18.weight = 20.0;
        c18.madeIn = "TN";
        c18.duration = 4;

        Crackers c19 = new Crackers();
        c19.name = "Pop Pop";
        c19.type = "Mini Sound";
        c19.price = 10.0;
        c19.isLoud = true;
        c19.isColorful = false;
        c19.brand = "KidsPop";
        c19.shape = "Ball";
        c19.weight = 5.0;
        c19.madeIn = "Delhi";
        c19.duration = 1;

        Crackers c20 = new Crackers();
        c20.name = "Boom Boom";
        c20.type = "Sound";
        c20.price = 65.0;
        c20.isLoud = true;
        c20.isColorful = false;
        c20.brand = "MegaBoom";
        c20.shape = "Tube";
        c20.weight = 115.0;
        c20.madeIn = "Nagpur";
        c20.duration = 3;
    }
}
